name: talants
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  sweetalert: ^0.0.1
  supercharged: ^1.11.0
  animations: ^1.1.2
  page_transition: ^1.1.7+2
  rounded_loading_button: ^1.0.15
  curved_navigation_bar: ^0.3.4
  webview_flutter: ^1.0.5
  onesignal_flutter: ^2.0.0
  auto_size_text: ^2.1.0
  mask_text_input_formatter: ^1.1.0
  cached_network_image: ^2.3.3
  flutter_svg: ^0.18.0
  flutter_masked_text: ^0.8.0
  flutter_date_pickers: ^0.1.5
  flutter_image_compress: ^0.7.0
  dotted_border: ^1.0.6
  uuid: any
  keyboard_visibility: any
  flutter_multi_formatter: ^1.1.6
  meta: ^1.1.6
  connectycube_sdk: ^0.5.0
  shared_preferences: ^0.5.8
  image_picker: ^0.6.7+4
  fluttertoast: ^3.1.3
  photo_view: ^0.5.0
  auto_size_text_field: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: IconsMaster
      fonts:
        - asset: fonts/IconsMaster.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

  assets:
    - assets/images/phone-off.svg
    - assets/images/home.svg
    - assets/images/phone-outgoing.svg
    - assets/images/fire.svg
    - assets/images/clock.svg
    - assets/images/statusIsUrgent.svg
    - assets/images/calendar.svg
    - assets/images/dot.svg
    - assets/images/plus.svg
    - assets/images/user.svg
    - assets/images/profile.svg
    - assets/images/logo.svg
    - assets/images/form.svg
    - assets/images/close.svg
    - assets/images/right-arrow.svg
    - assets/images/
    - assets/

  uses-material-design: true

