/// Flutter icons IconsMaster
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsMaster
///      fonts:
///       - asset: fonts/IconsMaster.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsMaster {
  IconsMaster._();

  static const _kFontFam = 'IconsMaster';
  static const _kFontPkg = null;

  static const IconData newspaper = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
